{% set name = "colourmap" %}
{% set version = "1.1.16" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/colourmap-{{ version }}.tar.gz
  sha256: 4b54405f894b910898a1babdc3c96f5bd2037f096cbccde9a106d85f21044c0e

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - pip
    - python >=3.6
  run:
    - matplotlib-base
    - numpy
    - python >=3.6

test:
  imports:
    - colourmap
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://erdogant.github.io/colourmap
  dev_url: https://github.com/erdogant/colourmap/
  summary: Python package colourmap generates an N unique colors from the specified input colormap.
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - thewchan
