{% set name = "colourmap" %}
{% set version = "1.1.20" %}

# Not set upstream but need this to be compatible with matplotlib >=3.10
{% set python_min = "3.10" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/colourmap-{{ version }}.tar.gz
  sha256: da40a71104bc92678bb420319b7fb0c65c2c872c5812b0712ed3b80b56617574

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - pip
    - python {{ python_min }}
    - setuptools
  run:
    - matplotlib-base >=3.10
    - numpy
    - python >={{ python_min }}

test:
  imports:
    - colourmap
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://erdogant.github.io/colourmap
  dev_url: https://github.com/erdogant/colourmap/
  summary: Python package colourmap generates an N unique colors from the specified input colormap.
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - thewchan
